FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y gcc git wget make libncurses-dev flex bison gperf libgtk-3-dev

COPY . /repo
ENV MODDABLE=/repo
WORKDIR /repo/build/makefiles/lin
RUN make -j8

FROM ubuntu:22.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libglib2.0-0
COPY --from=builder /repo/build/bin/lin/release/tools /
